language: scala

jdk:
- oraclejdk8

scala:
- 2.11.6

after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sbt ++$TRAVIS_SCALA_VERSION publish test:publish

env:
  global:
  - secure: Je1QhsJGoxF/UNdlnp99wxlyau8GEvFs74U1rx8ZI8dlYP3t0VIsUJhYdAWB69yo9n2+AXpnIyoZEx7KS5LmYOdKq0+AE69DYgkNQQBWfFWTbCC5TCr4nACdnkgUQ4T6+au64DBxqvttAvw21+k85DAjf5y13UVzPcplMsQ1OTo=
  - secure: BAJe05BL65jzvNwb1QHqgkN4pVNbLQTp6AGZOu3KvTggXtzFWLRwFBoaQKxNqI3v6i7kbCTqG5X//W8rPPSe0eo/CB6na6egQ0idfqYzor9CQlD0k7bfMQJ4nhoxGnM776I5U0h56oVSxOFi1K6rJRg3/itqXS+EXbyVZ3A0pNs=
